### ISSUE TITLE
Player/WeaponMixin MRO issues

### ISSUE THREAD

**Issue by CookStar** [Source-Python-Dev-Team/Source.Python#287] opened 2019-11-21 14:46 UTC
make_object(Player, pointer) no longer works after b580da22a6fc2fcf0ab36d5e7136bab94df99ee9
```python
# Source.Python
#   Weapons
from weapons.restrictions import weapon_restriction_handler
```

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
    make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
  File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 68, in on_player_bumping_weapon
    value = handler.on_player_bumping_weapon(player, weapon_name)
  File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 291, in on_player_bumping_weapon
    return not self.is_player_restricted(player, weapon)
  File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 313, in is_player_restricted
    if weapon_name in self.player_restrictions[player.userid]:

AttributeError: 'PlayerMixin' object has no attribute 'userid'
```

**Comment by jordanbriere** [comment] 2019-11-21 15:28
Derp, of course. The order have to be inverted, there is no doubt about that since currently, `Entity` resolves before `Player/WeaponMixin` and that really should be the opposite. Reverted that commit for now, and will do extensive testings on a separate branch. Will most certainly requires more explicit casting with the current multiple inheritance implementation. Thanks for spotting that.

**Comment by jordanbriere** [comment] 2019-11-21 23:25
Pushed a [new branch](https://github.com/Source-Python-Dev-Team/Source.Python/commit/0aea7acdf152d619d889f7e60a0728af6fd10ffe) with a potential fix.

The issue was caused by the fact `Player/WeaponMixin._obj` methods were `staticmethod` rather than `classmethod`, resulting into them always returning an instance of themselves regardless of the class. Wrapped them as `classmethod` and it seems to do the trick from my testings.

If you have a chance to build and test, please feel free to and let me know your results. Thanks!

**Comment by CookStar** [comment] 2019-11-22 06:54
make_object(Player, pointer) and make_object(Weapon, pointer) now works as expected!

```python
# Source.Python
#   Weapons
from weapons.restrictions import weapon_restriction_handler # No Error
```

```python
# Source.Python
#   Entities
from entities.hooks import EntityPreHook
from entities.hooks import EntityCondition
@EntityPreHook(EntityCondition.is_human_player, "bump_weapon")
def on_weapon_bump(args):
    player = make_object(Player, args[0])
    weapons = make_object(Weapon, args[1])
    print(player.name)
    print(weapons.weapon_name)
```
Output: 
```
Erik
weapon_glock
```

**Comment by jordanbriere** [comment] 2019-11-22 16:27
> make_object(Player, pointer) and make_object(Weapon, pointer) now works as expected!

Awesome!

After testing a bit more, I found a `TypeError` that should now be fixed into https://github.com/Source-Python-Dev-Team/Source.Python/commit/5ca16aa430ff0f8a5c488ac19dd0276a3429602c. Wasn't an issue at first, since I was casting the pointer directly but then I forwarded the call to their respective `__init__` method so they can handle the index validation, etc. But obviously, `object()` now had no idea what to do of a `shared_ptr`. So yeah, although caching the type proven to be slightly faster than forwarding back to the Python interpreter, I've removed that not only to fix that exception but also keeping python type references hostage seems to be a bad idea in general. Anyways, here is my current test code:

```python
from entities.entity import Entity
from entities.entity import BaseEntity
from memory import make_object
from memory import get_object_pointer
from _players import PlayerMixin
from players.entity import Player
from _weapons._entity import WeaponMixin
from weapons.entity import Weapon

pl = Player(1)
ptr = get_object_pointer(pl)

class MyPlayer(Player):
    pass

assert make_object(MyPlayer, ptr).__class__ is MyPlayer
assert make_object(Player, ptr).__class__ is Player
assert make_object(PlayerMixin, ptr).__class__ is PlayerMixin
assert make_object(Entity, ptr).__class__ is Entity
assert make_object(BaseEntity, ptr).__class__ is BaseEntity

ptr = pl.give_named_item('weapon_m4a1')

class MyWeapon(Weapon):
    pass

assert make_object(MyWeapon, ptr).__class__ is MyWeapon
assert make_object(Weapon, ptr).__class__ is Weapon
assert make_object(WeaponMixin, ptr).__class__ is WeaponMixin
```

**Comment by jordanbriere** [comment] 2019-11-22 16:58
Everything seems to be working as intended so that branch was merged to master. The following now resolves correctly:

```python
pl = Player(1)
Entity.test = property(lambda self: 'Entity')
assert pl.test == 'Entity'
PlayerMixin.test = property(lambda self: 'PlayerMixin')
assert pl.test == 'PlayerMixin'
```

Before inverting the base class order, the last assert would have failed because `Entity` would have been returned again.

Please re-open this issue if you find some more hidden issues related to that change. Thanks!

**Closed by jordanbriere** 2019-11-22 16:58 UTC
