### ISSUE TITLE
print() doesn't output anything/sys.stdout is None

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#175] opened 2016-12-29 16:15 UTC
Some people have reported that the ``print`` function doesn't output anything. The reason for this is that ``sys.stdout`` is ``None``.

I don't know why this happens, but this issue should be used to gather information about it.

**Where did this issue occur so far?**

- Windows 10 (TF2, CS:S, CS:GO)

**What I have tested so far (without being able to reproduce the issue):**

- Windows 7 (Blade, BM:S, CS:GO, CS:S, GMod, L4D2)
- Windows 10 (Freshly installed VM) (CS:S)
- Ubuntu 14.04.2 (Blade, BM:S, CS:GO, CS:S, GMod, L4D2)

Please post all relevant information here regarding this issue.

**Comment by Frag1337** [comment] 2017-02-17 00:22
any updates on that?

Windows traceback doesnt work either

**Comment by Ayuto** [comment] 2017-02-17 06:02
We have added a workaround that overrides sys.stdout when it's None, so that messages are printed through console_message.

If you are pertained by this issue, you should get a warning when starting your server with the appeal to post any relevant information regarding this issue.

And no, there are no news about this issue, because nobody has posted any information.

**Comment by KirillMysnik** [comment] 2017-04-25 12:56
I have this issue on CS:GO and now (when installed) on CS:S dedicated servers. Only after I switched to Windows 10. Never had this on Windows 7.

**Comment by Hackmastr** [comment] 2017-05-05 21:33
I just update, and I got this warning, so here's my info:

Windows 10,
CSS Dedicated server.
SP May, 02, current year.

**Comment by Frag1337** [comment] 2017-05-05 22:05
I just want to edit my first comment which included Windows traceback doesnt work. Its fixed with the latest GameThread change.

**Comment by neoncik** [comment] 2017-05-13 20:28
SP VERSION -> "sp_version" = "578" notify                                                      - Source.Python version
OS -> Windows Server 2016 Datacenter
GAME -> CS:GO

**Comment by xArchurious** [comment] 2017-09-25 03:48
OS: Windows-10-10.0.15063
Version: 592
Game: csgo

**Comment by invincibleqc** [comment] 2017-09-25 16:26
Seems like [sys documentation](https://docs.python.org/3/library/sys.html#sys.__stdin) has been updated to add the following note:
> Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.

**Comment by invincibleqc** [comment] 2017-10-08 12:36
Pushed a patch that fixed it on my side: https://github.com/Source-Python-Dev-Team/Source.Python/commit/49a5d7118f18c8418ac846e1c8835031f2b62dcd

@KirillMysnik @Hackmastr @Frag1337 @neoncik @xArchurious: If you guys could try updating your server(s) affected by this issue to build [747](http://builds.sourcepython.com/job/Source.Python%20-%20Building/747/) (or later), run the following code:


```python
import sys

print('sys.stdin =', sys.stdin)
print('sys.stdout =', sys.stdout)
print('sys.stderr =', sys.stderr)
```
And confirm that the streams are no longer pointing to `OutputRedirect` but correctly set to `TextIOWrapper` instances:

```
sys.stdin = <_io.TextIOWrapper name='CONIN$' mode='rt' encoding='utf-8'>
sys.stdout = <_io.TextIOWrapper name='CONOUT$' mode='wt' encoding='utf-8'>
sys.stderr = <_io.TextIOWrapper name='CONERR$' mode='wt' encoding='cp1252'>
```
It would be appreciated, thanks!

**Comment by satoon101** [comment] 2017-10-08 13:42
@invincibleqc - It looks good on my end, same output as you have.

**Comment by xArchurious** [comment] 2017-10-09 09:31
@invincibleqc - Yup, I got exactly the same thing!

**Comment by Ayuto** [comment] 2017-10-10 17:53
Awesome! Also works fine for me.

**Comment by invincibleqc** [comment] 2017-10-10 18:07
>I guess this can be closed.

I was hoping that @neoncik confirms it is also fixing the issue on *Windows Server 2016 Datacenter* but I guess we can close it either way. It should -- but who knows. Could always re-open it so whatever.

**Comment by Ayuto** [comment] 2017-10-10 18:27
Okay, I just had to realize that the fix doesn't work for listen servers. They still require the workaround.

**Comment by Hackmastr** [comment] 2017-10-10 18:50
@Ayuto listen servers are the clients right(css, not a dedi. server)? If it is, why care about those? 
SM does not even support them, why make so much work for something that won't be used that much.
I still play CSS/GO today and have never played on a listen server 😄

**Comment by Ayuto** [comment] 2017-10-10 19:00
>listen servers are the clients right(css, not a dedi. server)?

Yes, that's right. We partially support them as long as they don't cause much work. Disabling this fix for listen servers wasn't much work.

**Comment by invincibleqc** [comment] 2017-10-11 10:50
Makes sense, since listen servers are technically not attached to a terminal thus the channels are undefined. If we really wanted to, I guess we could inherit from String/BytesIO, wrap the buffer and redirect the operations but I really don't think it would worth the efforts. I'm fine with listen servers falling back to OutputRedirect.

**Closed** 2017-10-30 13:48 UTC
Labels: bug

**Comment by invincibleqc** [comment] 2018-02-06 20:29
Figured it out by accident while compiling another project. If the process that allocates the console (via `AllocConsole()`) is statically linked to the run-time library (built with `/MT`), and that the `Py_Initialize()` call is done outside of that process, [is_valid_fd]( https://github.com/python/cpython/blob/master/Python/pylifecycle.c#L1562-L1588) will fails and the streams won't be assigned. Easily reproducible by compiling a DLL with `/MT` and load another one that initializes Python. While our `source-python.dll` is statically linked to the run-time library, re-compiling it with `/MD` (after re-compiling the engine's libs) doesn't fix it for us because `srcds.exe` is statically linked. Redirecting to the channels works because these are opened into Windows' shared filesystem. Anyways, just thought I would share it here.
