### ISSUE TITLE
EntityIter - RunTimeError: Access violation - no RTTI data!

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#312] opened 2020-04-12 13:08 UTC
Hello,

I'm sometimes getting this error while iterating through EntityIter(). (Mostly after map change)

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\events\listener.py", line 92, in fire_game_event
    callback(game_event)
  File "..\addons\source-python\plugins\test\libs\misc\triggers.py", line 58, in round_start
    hook_triggers()
  File "..\addons\source-python\plugins\test\libs\misc\triggers.py", line 81, in hook_triggers
    for trigger_multiple in EntityIter('trigger_multiple'):
  File "..\addons\source-python\packages\source-python\filters\iterator.py", line 56, in __iter__
    if self._is_valid(item):
  File "..\addons\source-python\packages\source-python\filters\entities.py", line 65, in _is_valid
    elif self.exact_match and check_name == entity.classname:

RuntimeError: Access violation - no RTTI data!
```

**Comment by jordanbriere** [comment] 2020-04-12 15:17
Complete code?

**Comment by Frag1337** [comment] 2020-04-13 06:41
I will update this once I figgure out, how to reproduce it.

**Comment by jordanbriere** [comment] 2020-04-13 08:51
> I will update this once I figgure out, how to reproduce it.

I asked for your code to confirm, but I'm pretty sure this happens because your plugin must request an entity instance after the internal cache was invalidated (through an `OnEntityDeleted` callback that is called after SP's) resulting into freed entities being iterated over later on. This is something that is fixed into #292, but that branch haven't been reviewed as of yet and thus haven't been merged. If you can get it [compiled for your game/platform](http://wiki.sourcepython.com/contributing/building.html) and confirm everything is working as it used to or reports any issues you may notice it would be appreciated. Thanks!

**Comment by Frag1337** [comment] 2020-04-13 08:59
Thank you for the quick answer @jordanbriere! 

The code was simply an iterate through EntityIter, and I didnt wanted to post my whole private plugin in here, thats why I was trying to reproduce it but didnt succeed.

I actually had this same problem in the morning again, but it happened after my plugin failed to load, but as I said, I dont know how to reproduce it exactly.

Sadly I dont know how to recompile it, else I would help you out.

**Comment by Frag1337** [comment] 2020-04-13 09:00
That pull request looks also very interesting. Hope it gets pushed soon! Thanks for your work.

**Comment by jordanbriere** [comment] 2020-04-13 13:03
> I dont know how to reproduce it exactly.

It can be reproduced with the following code:

```python
from entities.entity import Entity
from listeners import OnEntityDeleted
from listeners.tick import Delay

# Create an entity, which will be internally cached
entity = Entity.create('info_null')

# Store its index
index = entity.index

@OnEntityDeleted
def on_entity_deleted(base_entity):
    # This listener is being called after SP's, meaning that
    # requesting an instance of this entity will cache a new
    # instance after it was invalidated
    Entity(base_entity.index)

# Remove the entity, which will call the above callback
entity.remove()

def print_classname(index):
    print(Entity(index).classname)

# Attempt to print the classname after the deletion was processed
Delay(1, print_classname, (index,))


"""
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 80, in _tick
    self.pop(0).execute()
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "..\addons\source-python\plugins\testing\testing.py", line 22, in print_classname
    print(Entity(index).classname)

RuntimeError: Access violation - no RTTI data!
"""
```

Which I assume is what happens for you; the entities are re-cached after the internal cache was invalidated, the indexes re-used by different entities on the new map and iterated over by `EntityIter`. On the other branch, that code is correctly throwing an exception rather than returning an instance that was re-cached after invalidation:

```python
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 80, in _tick
    self.pop(0).execute()
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "..\addons\source-python\plugins\testing\testing.py", line 22, in print_classname
    print(Entity(index).classname)
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 131, in __call__
    obj = super().__call__(index)
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 209, in __init__
    super().__init__(index)

ValueError: Conversion from "Index" (57) to "BaseEntity" failed.
```

**Comment by Frag1337** [comment] 2020-05-09 16:27
Looks like I still run into this problem.

On some occasion I'm getting this:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 194, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\debug\debug.py", line 4, in <module>
    for trigger_multiple in EntityIter('trigger_multiple'):
  File "..\addons\source-python\packages\source-python\filters\iterator.py", line 56, in __iter__
    if self._is_valid(item):
  File "..\addons\source-python\packages\source-python\filters\entities.py", line 65, in _is_valid
    elif self.exact_match and check_name == entity.classname:

RuntimeError: Access violation - no RTTI data!
```

with following code:

`from filters.entities import EntityIter


for trigger_multiple in EntityIter('trigger_multiple'):
    index = trigger_multiple.index
    target_name = trigger_multiple.target_name
`

`
Checksum      : a4fdf0d2adc411856c723f7d8aede00d
Date          : 2020-05-09 16:25:27.174220
OS            : Windows-10-10.0.18362
Game          : css
SP version    : None
Github commit : None
`

Notice I'm using your build from here: https://github.com/Source-Python-Dev-Team/Source.Python/pull/292#issue-346705840

**Comment by jordanbriere** [comment] 2020-05-09 16:38
Before or after https://github.com/Source-Python-Dev-Team/Source.Python/pull/292/commits/1b67129df4f531eb64e3624f6607d1d4f531526b? I've updated the builds yesterday after this commit, which was causing entities to only be cached if they carry the `EFL_NO_DISSOLVE` flag, regardless if they were marked for deletion or not. Make sure you use the `core.dll` from that build.

**Comment by Frag1337** [comment] 2020-05-09 16:42
I used the version before that. Let me try.

**Comment by Frag1337** [comment] 2020-05-09 16:57
@jordanbriere Looks like https://github.com/Source-Python-Dev-Team/Source.Python/commit/1b67129df4f531eb64e3624f6607d1d4f531526b fixxed that. Nice!

I dont get that error message after map change anymore.

**Closed** 2020-06-20 07:04 UTC
Labels: bug
