### ISSUE TITLE
Server sometimes crash on entity.remove()

### ISSUE THREAD

**Issue by Velocity-plus** [Source-Python-Dev-Team/Source.Python#158] opened 2016-10-13 12:42 UTC
**Description:**
- OS: Linux
- Game: Counter-Strike: Source

**Following code crashes server:**

``` python
from listeners.tick import Delay 

ENTITY_TARGET = "flashbang_projectile"

@OnEntityCreated
def EntityNaCreated(index, ptr):
    entity = Entity(index)
    if not entity.classname == ENTITY_TARGET:
        return
    entity.remove()  OR  Delay(1.40, entity.remove) # Triggers crash (sometimes) Usually after 5 - 10 min from when plugin is loaded


```

**Comment by invincibleqc** [comment] 2016-10-13 16:23
Please, always provide the following information when you report something:

- The game.
- The OS the server is running on.

This code alone should not crash. However, if you have multiple plugins that has a `OnEntityCreated` listener registered, removing the entity will cause the next callbacks to be called with no longer valid index and freed pointer causing them to handle invalid data and depending what they are doing, this may cause a crash. You don't want to remove the entity upon creation, instead, you want to block it from being created. By either grabbing a signature for `CreateEntityByName` or hook the `CEntityFactory::Create` method for the entity you are targeting. For the second, something like the following may work:

```python
from entities.factories import factory_dictionary
from memory import Convention
from memory import DataType
from memory import get_object_pointer
from memory import NULL
from memory.hooks import PreHook

ENTITY_TARGET = 'flashbang_projectile'
FACTORY_CREATE_OFFSET = 0

def get_entity_create_function(classname):
    factory = factory_dictionary.find_factory(classname)
    ptr = get_object_pointer(factory)
    return ptr.make_virtual_function(FACTORY_CREATE_OFFSET,
        Convention.THISCALL,
        (DataType.POINTER, DataType.STRING), DataType.POINTER)

@PreHook(get_entity_create_function(ENTITY_TARGET))
def pre_flashbang_projectile_create(stack_data):
    if stack_data[1] == ENTITY_TARGET:
        return NULL
```

However, being untested, I assume it will crash since if I remember right, the factories creation functions are using a custom calling convention (at least, on windows). Test it, and let me know. If it doesn't work, and once you have provided the info listed above, I will try to grab a signature for the game you are coding for.

**Comment by invincibleqc** [comment] 2016-10-13 16:28
Also, we are still waiting you to answer questions on #157. That being said, I don't think that creating an issue for every crash that you are encountering is the way to go. You should rather post on the forums and create issues when it has be confirmed to be a bug within Source.Python and not a misuse of the features or a clash between plugins.

**Comment by Velocity-plus** [comment] 2016-10-13 16:49
You are right, but it doesn't seem like there are a issue/bug section on the forums, so I'm not sure where to post. That being said, I intended to do `Delay(1.40, entity.remove)`, which also crashes the server.

**Comment by maduxthemad** [comment] 2016-10-13 17:42
mhh testing this on my server (windows) i found, that "OnEntityCreated" in SP runs two times? i also found that "@OnEntityPreSpawned" never gets run? ( is there some sort of internal mixup? ) this might be a different issue now, as removing still runs fine ony ms server, just wanted to bring it up to someone who might have insight to this. ill debug this myself right now and report back soon. 

and btw, you could just use this code to workaround re-creating Entity:

```
from listeners import OnEntityCreated
ENTITY_TARGET = "flashbang_projectile"
@OnEntityCreated
def on_entity_created(index, base_entity):
	if base_entity.classname == ENTITY_TARGET:
		baseentity.remove()
```

**Comment by satoon101** [comment] 2016-10-13 17:53
I'm not sure why OnEntityCreated is called twice, but OnEntityPreSpawned is a BMS only listener:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/daf06d0532b2be2a2a57b292e18364baec988c10/src/core/sp_main.h#L101

That functionality does not exist in any other engine, so of course it won't be called unless you are running BM:S.

**Comment by Velocity-plus** [comment] 2016-10-13 18:10
```python
from listeners import OnEntityCreated
ENTITY_TARGET = "flashbang_projectile"
@OnEntityCreated
def on_entity_created(index, base_entity):
    if base_entity.classname == ENTITY_TARGET:
        base_entity.remove()
```
If the reply is for me. I'm not sure what the difference in code compared to what I posted?

**Comment by Ayuto** [comment] 2016-10-13 18:12
> We should definitely add that to the documentation, though, to make it clear.

It's documented! :)
http://wiki.sourcepython.com/developing/module_tutorials/listeners.html#onentityprespawned

> I'm not sure what the difference in code compared to what I posted?

The difference is that it's using the second argument (BaseEntity instance) to remove the entity. There is no need to create an Entity instance at first.

**Comment by Velocity-plus** [comment] 2016-10-13 20:39
Arh I see it now XD, its the second parameter in `def on_entity_created (index, base_entity)`, sorry I'm blind today.

**Comment by Velocity-plus** [comment] 2016-10-15 00:25
@invincibleqc I tested it and it crashed the server and that is linux as os.

**Comment by Ayuto** [comment] 2016-10-17 17:16
Just tested this with 12 bots for 15 minutes on de_dust2 and and then left the server and the bots continued playing on the server for ~2 hours. I didn't experience any crash.

**Comment by Velocity-plus** [comment] 2016-10-19 13:01
I think it was trikz_cyrus

**Comment by Ayuto** [comment] 2016-10-20 11:37
Do you have a download link for me? Also, which SP version are you using?

**Comment by Velocity-plus** [comment] 2016-11-05 00:32
http://gamebanana.com/maps/155380

**Comment by Ayuto** [comment] 2016-12-04 14:10
I'm still unable to reproduce the crash. Thus, I will close this issue.

**Closed** 2016-12-04 14:10 UTC
Labels: invalid
