### ISSUE TITLE
CS:S - OnServerOutput Crash

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#404] opened 2021-08-23 00:38 UTC
EDIT: Please check https://github.com/Source-Python-Dev-Team/Source.Python/issues/404#issuecomment-904157804

Hello,

I'm currently having an issue where Source.Python crashes when two player's are inside the same trigger_push entity.

This is the console log:
```
2021-08-22 06:44:52 - sp    -    EXCEPTION    
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\SurfTricks\libs\misc\hooks.py", line 101, in on_touch_pre
    entity = make_object(Entity, args[1])
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 293, in _obj
    return cls(index_from_pointer(ptr))

ValueError: Conversion from "Pointer" (<_memory.Pointer object at 0x011F5C50>) to "Index" failed.

<=> CRASH <=>
```

Code:
```python
@EntityPreHook(EntityCondition.is_human_player, "touch")
def on_touch_pre(args):
    player = make_object(Entity, args[0])
    entity = make_object(Entity, args[1])
```

sp info:
```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 5e3156dad6f48fe59901274827251ec8
Date          : 2021-08-23 00:36:57.404125
OS            : Windows-10-10.0.19041
Game          : css
SP version    : 705
Github commit : 38e4fe48579f9445b878624a9439ce10e28aa7e6
Server plugins:
   00: Metamod:Source 1.12.0-dev+1145
   01: Source.Python, (C) 2012-2020, Source.Python Team.
   02: Tickrate_Enabler 0.4, Didrole
SP plugins:
   00: SurfTricks, 1.6, http://trick.surf
--------------------------------------------------------
```

**Comment by jordanbriere** [comment] 2021-08-23 19:35
It's very unlikely that the exception itself is related to the crash you are encountering and probably just means the touching entity isn't networked. Try using `BaseEntity` instead or catch the exception and exit the call. That said, my first guess as far as the crash is concerned would be a clash between SP's and SM's hook. Try with only SP installed as well as only a minimal reproducible plugin loaded and see if you are still crashing.

**Comment by Frag1337** [comment] 2021-08-23 21:50
Thank you for your reply. You are right, it isn't actually the cause, it was just find through the error log.

So I've tried to debug the exact cause why this crash was happening, since it was reproducable. I've started with disabling Metamod + Sourcemod, it was still crashing, disabled 100 Tick Enabler, it was still crashing, disabled everything related to hooking in my Source.Python plugin, and it was still crashing.. Hmm, I went further ahead and finally found the cause for it, which I would never thought of.

sp info
```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 9ef93fdfb37c25f134642a2fd0231d68
Date          : 2021-08-23 21:45:24.462681
OS            : Windows-10-10.0.19041
Game          : css
SP version    : 705
Github commit : 38e4fe48579f9445b878624a9439ce10e28aa7e6
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
   00: test
--------------------------------------------------------
```

test/test.py
```python
from listeners import OnServerOutput
from core import OutputReturn

@OnServerOutput
def on_server_output(severity, message):
    if message.startswith("test123456"):
        return OutputReturn.BLOCK
```

I have no idea why OnServerOutput is crashing the server, when two players enter a trigger_push, but atleast I found the cause.

I can upload video of proof in some minutes.

**Comment by jordanbriere** [comment] 2021-08-23 22:17
Similar crashes related to the output listener were reported into #400. But since you provided more context I guess we can continue the discussion here until we know more. For now, two questions come to mind;

- Do you crash if you don't call `startswith`?
- Do you crash if you don't block the output?

**Comment by Frag1337** [comment] 2021-08-23 23:05
I will try tomorrow, thanks for your fast reply.

**Comment by Frag1337** [comment] 2021-08-24 19:47
```python
from listeners import OnServerOutput
from core import OutputReturn

@OnServerOutput
def on_server_output(severity, message):
    OutputReturn.CONTINUE
```

This is crashing aswell, so this would answer both of your questions.

**Comment by jordanbriere** [comment] 2021-08-24 20:05
Hmmm. What about this: [core.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7041832/core.zip)?

**Comment by Frag1337** [comment] 2021-09-01 02:06
Thank you for your effort you two!

Always very appreciated. Should I close this? @jordanbriere

**Comment by jordanbriere** [comment] 2021-09-01 10:32
> Should I close this? @jordanbriere

We can keep it open until what to do with it is decided. I'm personally not too keen on just knowingly leaving a crash if it can be prevented without server owners having to change their configuration.

**Comment by NosferatuJoe** [comment] 2021-09-02 19:28
Hey everyone. Quite interesting to see the same crash issue  that I was having. I was just curious how ya'll fixed the startswith server crash? Is using DT_warning_blocker together with the patcher.py enough? Not sure what the latter one does though..

**Comment by NosferatuJoe** [comment] 2021-09-02 19:31
> So, I've tried a few things without any success. I don't think this is something we can straightforwardly fix on our side and would likely requires some hacky approaches such as storing the outputs and handling them later. This seems to be another of many issues caused by the engine's parallelization. For the same reason you will crash if you hook a send prop's proxy unless you have `sv_parallel_packentities 0` in your `autoexec.cfg`.

Sorry for being off-topic on this one but I'm just wondering: Is this why "es playerset model" using a prop crashes all clients on player death?

**Comment by jordanbriere** [comment] 2021-09-03 02:06
> 
> 
> Hey everyone. Quite interesting to see the same crash issue that I was having. I was just curious how ya'll fixed the "startswith" server crash? Is using DT_warning_blocker together with the patcher.py enough? Not sure what the latter one does though..

CookStar's plugin will prevent the specific context discussed in this thread. However, different contexts may also cause a crash if our logging listener is called from the parallel thread with different outputs. An universal way that would cover all cases would be for you to set `sv_parallel_packentities 0` in your `autoexec.cfg` at the cost of networking optimization losses, unfortunately.

> Sorry for being off-topic on this one but I'm just wondering: Is this why "es playerset model" using a prop crashes all clients on player death?

Unrelated. Clients are likely crashing because the model you did set cannot be ragdollified.

**Comment by CookStar** [comment] 2021-09-05 02:06
> I was just curious how ya'll fixed the "startswith" server crash?

As jordanbriere wrote, dt_warning_blocker only prevents the crash in this particular case.
When the DataTable value exceeds the Max or Min value, `DataTable_Warning` function is called and warning will be output, however, dt_warning_blocker overrides `DataTable_Warning` function and prevents the execution. As the result, it will not output a warning and `OnServerOutput` listener will not be dispatched. But be aware this is not suitable if you want to handle the processing at the Python side.

> Is using DT_warning_blocker together with the patcher.py enough?

If you have a ServerOutput that can't prevent crashes with dt_warning_blocker, and can reproduce the crashes precisely, please open an issue at https://github.com/CookStar/SmallLib. If possible, I will create a plugin to prevent crashes.

**Comment by jordanbriere** [comment] 2021-09-05 10:32
Pushed a fix into: https://github.com/Source-Python-Dev-Team/Source.Python/commit/109ccc6acce6c803e22b9b8f8cf36ae19ad60f6b. Only tested on Windows/CS:S/CS:GO. Here is a CS:S build that no longer crash with the context posted above: [core.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7111413/core.zip), @Frag1337. If you guys can get it compiled/tested on other games/platforms please let me know how it goes. Thanks!

**Comment by NosferatuJoe** [comment] 2021-09-05 18:49
I would love to test it on linux and CSGO but I have no clue how to compile SP. I've already tried with ubuntu 20.4, but I have no linux knowledge and there is no guide as how to. Whenever there's a compiled linux version I'd gladly test it out.

**Comment by CookStar** [comment] 2021-09-06 12:15
> If you guys can get it compiled/tested on other games/platforms please let me know how it goes.

It compiled and worked fine on CS:S/Windows, but what about Linux?
Why not use CThreadMutex?

> I would love to test it on linux and CSGO but I have no clue how to compile SP. I've already tried with ubuntu 20.4, but I have no linux knowledge and there is no guide as how to. Whenever there's a compiled linux version I'd gladly test it out.

I don't think this fix is intended for Linux, so we can't try it on Linux.

**Comment by jordanbriere** [comment] 2021-09-06 12:19
> It compiled and worked fine on CS:S/Windows, but what about Linux?
> Why not use CThreadMutex?

Pushed that 2 hours ago. 😄 

→ https://github.com/Source-Python-Dev-Team/Source.Python/commit/ffef7006f27f2cdb16c41ecee47cdc057f443db7

**Comment by CookStar** [comment] 2021-09-06 13:53
Oh, bad timing.

However, the return values of Msg and printf are different, so it cannot be compiled with GCC.
```
../srcds/Source.Python/src/core/utilities/sp_util.h:55:48: error: second operand to the conditional operator is of type ‘void’, but the third operand is neither a throw-expression nor of type ‘void’
   bLogged ? Msg("%s", pMsg) : printf("%s", pMsg);
                                                ^
```

**Comment by jordanbriere** [comment] 2021-09-06 14:01
> 
> 
> Oh, bad timing.
> 
> However, the return values of Msg and printf are different, so it cannot be compiled with GCC.
> 
> ```
> ../srcds/Source.Python/src/core/utilities/sp_util.h:55:48: error:
> second operand to the conditional operator is of type ‘void’,
> but the third operand is neither a throw-expression nor of type ‘void’
>    bLogged ? Msg("%s", pMsg) : printf("%s", pMsg);
>                                                 ^
> ```

Thanks, should be good now.

**Comment by Frag1337** [comment] 2021-09-16 19:27
@jordanbriere I'm very sorry for the late response.

Its not crashing anymore on CS:S with your updated `core.dll` (https://github.com/Source-Python-Dev-Team/Source.Python/files/7111413/core.zip). Thank you!

I've used the same test plugin which previously crashed on using `test_teleport`. But are you sure this error isn't also related to linux? I think I tested it on Linux aswell. Sadly I cannot update my servers using `sp update` since Source.Python seems to be down, but I will once its back up.

**Comment by CookStar** [comment] 2021-09-17 00:32
> But are you sure this error isn't also related to linux?

With the new fix, I don't think it will crash on linux. However, I can't say for sure because I have not been able to reproduce the crash on Linux in the first place.

> I think I had crashes on Linux aswell, but I will try to test it on Linux aswell once Source.Python is back up again. Sadly I cannot update my servers right now using `sp update`.

If you want to test server_output on Linux as well, you can try my binaries([core.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7181665/core.zip)), but if you don't want to do that, you'll have to compile it yourself or wait for @jordanbriere.

**Comment by jordanbriere** [comment] 2021-09-20 09:40
> But are you sure this error isn't also related to linux?

While yes, that platform is also affected, it may or may not crash in this specific context because the behaviours are basically undefined. Based on my minimal testings I did at the time, the problem appeared to be the string being interned by the interpreter and the object being shared for both calls being freed before one or the other had properly incref'ed it resulting into a crash when accessed and/or freed for the second time.

**Comment by NosferatuJoe** [comment] 2021-09-20 22:22
> > But are you sure this error isn't also related to linux?
> 
> With the new fix, I don't think it will crash on linux. However, I can't say for sure because I have not been able to reproduce the crash on Linux in the first place.
> 
> > I think I had crashes on Linux aswell, but I will try to test it on Linux aswell once Source.Python is back up again. Sadly I cannot update my servers right now using `sp update`.
> 
> If you want to test server_output on Linux as well, you can try my binaries([core.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7181665/core.zip)), but if you don't want to do that, you'll have to compile it yourself or wait for @jordanbriere.
> 
> P.S. Now I see what you mean.

Thank you for the files. I'll be testing it tomorrow on my linux csgo server.

**Comment by NosferatuJoe** [comment] 2021-09-25 12:48
I can confirm that @CookStar 's binaries for Linux seem to fix this issue. My server runs fine without any crashes. I even reverted the changes to the normal .so & bin files and server starts crashing immediately.

**Comment by Frag1337** [comment] 2021-09-25 13:09
Awesome!

Hopefully we can get a new official build with this fix soon!

**Comment by NosferatuJoe** [comment] 2021-09-25 22:00
UPDATE:

According to a player report my server crashed multiple times a day and even multiple times in a row. I can confirm that this might've been the case as my server is currently offline due to 10 consecutive crashes in a row. So the fix might not be 100% on Linux, I will investigate this further and provide as much details as I can on this subject.

**Comment by NosferatuJoe** [comment] 2021-09-25 22:51
I can also upload a crashdump.dmp but I need a trustworthy fileshare service. If needed recommend me one and I'll upload it right away.

**Comment by jordanbriere** [comment] 2021-09-26 00:21
> Hopefully we can get a new official build with this fix soon!

The [latest build](http://downloads.sourcepython.com/) includes https://github.com/Source-Python-Dev-Team/Source.Python/commit/e6920e13b969d10d2112770af9c3fe64ab8a3922 which addresses the crash caused by this issue. You won't be able to filter outputs that are sent from a parallel thread anymore, but it won't crash as they are simply ignored.

> I can also upload a crashdump.dmp but I need a trustworthy fileshare service. If needed recommend me one and I'll upload it right away.

Your crash doesn't seem to be related. The issue discussed in that thread doesn't throw a `boost::python::error_already_set` error whatsoever. Moreover, this error should not really cause the process to terminate as it is usually picked up and forwarded to the Python interpreter translated to an exception. The only scenario I know this would happens, is if you are running SP along a specific SM extension (#321). As for your dumps, just zip them and attach the zip directly to your post here.

**Comment by NosferatuJoe** [comment] 2021-09-26 09:50
Here the latest crash dump that should be linked to the console.log snippet I sent:
[crash_20210925202156_1.zip](https://github.com/Source-Python-Dev-Team/Source.Python/files/7231138/crash_20210925202156_1.zip)

**Comment by jordanbriere** [comment] 2021-09-26 10:40
> I just installed the latest available SP build and then added Cookstar's binaries on top.

It doesn't really matter this time since there was no critical changes between both branches (besides some fixes on the wiki) in that time frame but for future reference; this is something you should never do. If you use binaries compiled from a specific branch, then you should use everything else because some changes on the Python side might be incompatible with some on the C++ side or vice-versa.

That said, it's very unlikely that your crash loop is caused by this issue. Easy to confirm, though. Add the following to your `autoexec.cfg` and if you still crash it means it has nothing to do with it. You should then track the issue by elimination; disable SM, test, disable all your SP plugins, test, enable one plugin, test, another one, test, etc. until the crashes come back so you know where to start looking.

**Comment by NosferatuJoe** [comment] 2021-09-26 12:25
> > I just installed the latest available SP build and then added Cookstar's binaries on top.
> 
> It doesn't really matter this time since there was no critical changes between both branches (besides some fixes on the wiki) in that time frame but for future reference; this is something you should never do. If you use binaries compiled from a specific branch, then you should use everything else because some changes on the Python side might be incompatible with some on the C++ side or vice-versa.
> 
> That said, it's very unlikely that your crash loop is caused by this issue. Easy to confirm, though. Add the following to your `autoexec.cfg`: `sv_parallel_packentities 0` and if you still crash it means it has nothing to do with it. You should then track the issue by elimination; disable SM, test, disable all your SP plugins, test, enable one plugin, test, another one, test, etc. until the crashes come back so you know where to start looking.

So that means, that the fixes are already applied on the 21 september build? I have that one running now and will let you know if it still crashes after I use the onserveroutput code

**Comment by NosferatuJoe** [comment] 2021-09-26 12:39
I can confirm that this piece of code in the WCS mod does not crash the server anymore on CSGO after using latest SP build:

```
# Is ESC supported?
if IS_ESC_SUPPORT_ENABLED:
    #  Used to clean up loading/unloading of wcs
    @OnServerOutput
    def on_server_output(severity, msg):
        if msg.startswith(('[EventScripts] Loaded wcs/modules/races/', 'Unloading wcs/modules/races/')) or (msg.startswith('wcs/modules/races/') and msg.endswith(' has been unloaded\n')):
            return OutputReturn.BLOCK
        if msg.startswith(('[EventScripts] Loaded wcs/modules/items/', 'Unloading wcs/modules/items/')) or (msg.startswith('wcs/modules/items/') and msg.endswith(' has been unloaded\n')):
            return OutputReturn.BLOCK

        return OutputReturn.CONTINUE
```

```
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : b9ee5c091e712e73e470b2e014ea2225
Date          : 2021-09-26 12:39:19.538046
OS            : Linux-5.9.0-1-amd64-x86_64-with-debian-10.10
Game          : csgo
SP version    : 708
Github commit : 70e71fe6531e655fd164d40bea7c838c447199c0
Server plugins:
   00: Source.Python, (C) 2012-2021, Source.Python Team.
   01: Metamod:Source 1.11.0-dev+1145
SP plugins:
   00: adaptive_radar
   01: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
   02: wcs, 2021.03.30-1, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
   03: commandsx
--------------------------------------------------------
```

**Comment by jordanbriere** [comment] 2021-09-26 15:01
> So that means, that the fixes are already applied on the 21 september build?

The official build includes a patch that prevent the crash by no longer processing outputs that are not from the main thread while the `server_output` branch process all outputs but ensure there is no crash by locking the shared resources (the interned `PyObject` of the output itself) so that simultaneous calls don't release memory until the others are done with it. So yes, both should no longer crash when multiple threads send the exact same output at the exact same time.

**Closed** 2021-12-03 03:38 UTC
