### ISSUE TITLE
Re-Iteration of the Offset in CCSPlayer offsets. (CSGO)

### ISSUE THREAD

**Issue by Grubbsy1896** [Source-Python-Dev-Team/Source.Python#388] opened 2021-03-20 14:29 UTC
MVP, Kills, Assists, and such all have updated offsets, at least from the current ones listed. 

addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini

![image](https://user-images.githubusercontent.com/64875911/111873549-c3cf3580-895e-11eb-89d7-bd3cea18a8f6.png)

**Comment by CookStar** [comment] 2021-03-20 16:48
These offsets are no longer needed by 9d6c9e07b95cc6eef900c69dc5220d3682e7c2d1.
It's been off by almost a month, but there doesn't seem to be any problem.

**Comment by jordanbriere** [comment] 2021-03-20 18:24
> It's been off by almost a month, but there doesn't seem to be any problem.

If servers are running an updated SP build then the `based_attribute` are being prioritized, but for those that aren't they are still using the `instance_attribute` (which was the reason they were left in the file, so that live servers don't pull a data update removing attributes until they update their whole installation). However, if the `instance_attribute` are no longer valid, then they can now be removed and it is time for servers to update if they didn't.

Just one thing before I get that merged in, are the `based_attribute` confirmed to still be valid?

Thanks!

**Comment by CookStar** [comment] 2021-03-20 19:07
> If servers are running an updated SP build then the `based_attribute` are being prioritized, but for those that aren't they are still using the `instance_attribute` (which was the reason they were left in the file, so that live servers don't pull a data update removing attributes until they update their whole installation). However, if the `instance_attribute` are no longer valid, then they can now be removed and it is time for servers to update if they didn't.

Oh yes, I had forgotten about those who have not updated their Source.Python.
I probably should have deleted it much earlier.

> Just one thing before I get that merged in, are the `based_attribute` confirmed to still be valid?

Yes.

**Closed** 2021-03-20 19:33 UTC
