### ISSUE TITLE
Set Transmit crashes on certain maps

### ISSUE THREAD

**Issue by Velocity-plus** [Source-Python-Dev-Team/Source.Python#264] opened 2018-11-20 21:19 UTC
OS: Linux
Game: CS:GO

Example map that crashes: **trikz_advanced_csgo** 
Download: https://gamebanana.com/maps/170864

```
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 5a60a1bae2f27f62a5aa05e68b7c835b
Date          : 2018-11-20 22:24:42.974079
OS            : Linux-4.15.0-38-generic-x86_64-with-debian-buster-sid
Game          : csgo
SP version    : 667
Github commit : 4b4d6a886456e7f59793af7ca0a9d2f098683b78
Server plugins:
   00: Source.Python, (C) 2012-2018, Source.Python Team.
   01: Metamod:Source 1.10.7-dev
SP plugins:
   00: transmit
--------------------------------------------------------

```

Nothing else was loaded with this code, I made a new file called transmit.py with the only following code 
```python
from entities.hooks import EntityCondition
from entities.hooks import EntityPreHook
from messages import SayText2
from players.entity import Player
from entities import CheckTransmitInfo
from entities.entity import BaseEntity
from memory import make_object
from entities.helpers import index_from_edict

@EntityPreHook(EntityCondition.is_not_player, 'set_transmit')
def pre_set_transmit(args):
        entity = make_object(BaseEntity, args[0])
        edict = make_object(CheckTransmitInfo, args[1]).client

        player = Player(index_from_edict(edict))
        # We always transmit the player to himself. If we don't, bad things happen.
        if player.index == entity.index:
            return None
```
It doesn't matter what EntityCondition is or if I use PreHook instead of EntityPreHook AND it does not matter what is inside the transmit function as long as transmit is hooked. This code crashes my server in many maps, a few maps do work, but I think there must be something wrong with PreHook.

**Comment by Ayuto** [comment] 2018-11-20 21:57
What's the output of ``sp info``? Also please include the imports in future. There is no reason to not include them unless you want to bother me. ;-)

**Comment by Ayuto** [comment] 2018-11-21 11:50
Please also test it without Metamod/Sourcemod. This ensures a minimalistic testing environment.

**Comment by Velocity-plus** [comment] 2018-11-21 14:09
Tested with only SourcePython, with only 1 file with this code. It still crashes :(

**Comment by Velocity-plus** [comment] 2018-11-22 02:59
I have figured out why the crash was happening. When these two entities are being transmitted the server crashes (If the map contains these)

------ CRASHED REPORT ----
Entity CLASSNAME: env_smoke
Entity CLASSNAME: _firesmoke
------ CRASHED --------------

**Comment by Velocity-plus** [comment] 2018-11-26 20:44
After further testing I have narrowed down the list:

`python
crash_entities = ('env_fire', '_firesmoke', 'env_laser', 'func_rotating', 'prop_dynamic')
`
A work-around would be to check if entity is in crash_entities and then just `return False`

**Comment by Velocity-plus** [comment] 2019-01-13 02:49
Would be great if the issue could have some kind of priority since set_transmit is awesome.

**Comment by jordanbriere** [comment] 2019-11-22 18:54
Closing as this was fixed into https://github.com/Source-Python-Dev-Team/Source.Python/commit/74c2b0189c4b0620a4e7be2680d73af509fbc249. I've tested that map with your code just now and it is not crashing. After checking the SDK, that method is indeed internally calling itself for its parent: [baseentity.cpp#L3660-L3664](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/server/baseentity.cpp#L3660-L3664). So it was pretty much the same as the issue [here](https://forums.sourcepython.com/viewtopic.php?f=20&t=1447&p=9615&hilit=memory+make+object+crash#p9615).

**Closed by jordanbriere** 2019-11-22 18:54 UTC
Labels: bug

**Comment by Velocity-plus** [comment] 2019-11-28 20:05
@jordanbriere Can you briefly explain, what you mean by it was internally calling itself for its parent. I'm just curious how this got fixed because that was a very important issue (for my plugins at least).

**Comment by jordanbriere** [comment] 2019-11-29 06:49
> 
> 
> @jordanbriere Can you briefly explain, what you mean by it was internally calling itself for its parent. I'm just curious how this got fixed because that was a very important issue (for my plugins at least). So that is cool.

Suppose that function was written in Python, it would be something like this:

```python
def set_transmit(entity):
    if entity.parent:
        set_transmit(entity.parent)
```

This would normally not be an issue, but the nested call caused a crash on Linux because at the time the alignment of the stack wasn't properly preserved within the hook. Ayuto fixed that into [DynamicHooks](https://github.com/Ayuto/DynamicHooks) and now it is working as intended. 😃
