### ISSUE TITLE
player.is_hltv() return False for GOTV

### ISSUE THREAD

**Issue by slav0nic** [Source-Python-Dev-Team/Source.Python#168] opened 2016-12-02 15:13 UTC
Tested with csgo server and latest source.python (2 dec)

```python
@Event('player_activate')
def player_activate(game_event):
    player = Player(index_from_userid(game_event['userid']))
    print(player.is_hltv(), player.name)
    ...
```
server logs:
```
...
L 12/02/2016 - 18:11:13: "GOTV<2><BOT><>" entered the game
[AM]: player_activate START
False GOTV
```

**Comment by Ayuto** [comment] 2016-12-10 10:58
It seems like the flag hasn't been set yet in that event. Later, if you iterate over all players for example, it's working fine. However, my tests have shown that it's the first player that connects to your server. So, all you need to do is checking if ``tv_enable`` is set to ``1`` and if it's the first player that is connecting.

**Comment by jordanbriere** [comment] 2021-12-07 22:54
Since this is not really an issue caused by Source.Python, I will go ahead and close this issue. I've added a note about it to `Player.is_hltv`'s docstring so that at least it is documented on the wiki.

**Closed by jordanbriere** 2021-12-07 22:54 UTC
