### ISSUE TITLE
BaseEntity.solid_flags shouldn't be exported as a SolidFlags_t.

### ISSUE THREAD

**Issue by McYoloSwagHam** [Source-Python-Dev-Team/Source.Python#331] opened 2020-05-08 19:26 UTC
the enum <SolidFlag_T> only allows you to assign one value from SolidFlags.Value to an entities SolidFlag, where as in the game you can have multiple SolidFlags switches turned on and off using BitMasks.

**Comment by jordanbriere** [comment] 2020-05-08 19:52
Actually, you were right so I've restored your report. The issue is not the enumerator itself, but the `BaseEntity.solid_flags` should rather be interpreted as `unsigned short`, instead of `SolidFlags`. The `SolidFlags_t` enumerator is only a namespace, and the engine interprets that property as an `unsigned short` so should we. Thanks for spotting that, will push a fix shortly.

**Comment by jordanbriere** [comment] 2020-05-08 20:01
Fixed into https://github.com/Source-Python-Dev-Team/Source.Python/commit/c28565b0cf750cb22f48683054e3d1c853770bbe.

**Closed by jordanbriere** 2020-05-08 20:01 UTC
