### ISSUE TITLE
Loading keygroups in cstrike/resource crashes the server

### ISSUE THREAD

**Issue by kamikazekuh** [Source-Python-Dev-Team/Source.Python#379] opened 2021-01-22 21:54 UTC
Using this code to load the cstrike_english.txt keygroup crashes the server on windows

```
from core import GAME_PATH
from _keyvalues import KeyValues

messages = KeyValues.load_from_file(GAME_PATH / 'resource' / 'cstrike_english.txt')
```

**Comment by jordanbriere** [comment] 2021-01-23 03:42
The issue appears to be the encoding of those files causing an access violation when the engine parses them (by failing to decoding them and internally handling a `NULL` pointer). If I change the encoding of that file to `UTF-8`, it works as intended. Same if I export `LoadFromBuffer` and parse it as `UTF-16`:

```python
kv = KeyValues('lang')
with open(GAME_PATH / 'resource' / 'cstrike_english.txt', encoding='utf-16') as f:
    kv.load_from_buffer(f.read())
print(kv)
```

**Comment by Ayuto** [comment] 2021-01-31 09:54
There also seems to be an issue with parsing that file:
```python
from keyvalues import KeyValues
from paths import GAME_PATH

kv = KeyValues('lang')
with open(GAME_PATH / 'resource' / 'cstrike_english.txt', encoding='utf-16') as f:
    kv.load_from_buffer2(f.read())
    
print(kv.as_dict())
```
```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 207, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\test7\test7.py", line 8, in <module>
    print(kv.as_dict())

KeyError: "Key 'Radio Responses/Reports\n\n1. \\' does not exist."
```

**Comment by jordanbriere** [comment] 2021-01-31 10:09
You probably have to specify the use of escaped sequences before parsing it:

```python
kv.uses_escape_sequences(True)
```

**Comment by Ayuto** [comment] 2021-01-31 10:17
Ah yes, that solves the problem.

**Comment by Ayuto** [comment] 2021-02-09 20:32
Are we going to change anything or do we keep it like it is?

**Comment by jordanbriere** [comment] 2021-02-09 21:56
> 
> 
> Are we going to change anything or do we keep it like it is?

I guess we could simply use Python to parse the file. Perhaps something like this:

```cpp
.def("load_from_file",
	raw_function(&KeyValuesExt::LoadFromFile, 1),
	"Load KeyValues data from a file and return a new KeyValues instance on success."
).staticmethod("load_from_file")

.def("load_from_file2",
	raw_method(&KeyValuesExt::LoadFromFile2, 1),
	"Load KeyValues data from a file into an existing KeyValues instance."
)
```
```cpp
static boost::shared_ptr<KeyValues> LoadFromFile(boost::python::tuple args, dict kwargs)
{ 
	KeyValues* pKeyValues = new KeyValues("");
	if (!KeyValuesExt::LoadFromFile2(pKeyValues, args, kwargs)) {
		pKeyValues->deleteThis();
		BOOST_RAISE_EXCEPTION(PyExc_ValueError, "Failed to load from file.")
		return NULL;
	}
	return boost::shared_ptr<KeyValues>(pKeyValues, &__del__);
}

static object LoadFromFile2(KeyValues* pKeyValues, boost::python::tuple args, dict kwargs)
{ 
	static object io_open = import("io").attr("open");
	object f = io_open(*args, **kwargs);
	bool result = LoadFromBuffer2(pKeyValues, extract<const char *>(f.attr("read")()));
	f.attr("close")();
	return object(result);
}
```

Now one could do something like this:

```python
# Raises an encoding error, but ignore it and produce an empty keyvalues
kv = KeyValues.load_from_file(path, errors='ignore', encoding='utf-8')

# Works (except for the escape sequences)
kv = KeyValues.load_from_file(path, encoding='utf-16')

# Engine produce a parse error instead of crashing:
#   KeyValues Error: LoadFromBuffer: missing { in file
kv = KeyValues.load_from_file(path)
```

Simple yet efficient! Only downside, would probably be the path resolution (e.g. `resource/cstrike_english.txt` would no longer resolves). Perhaps there's a way to resolve relative paths from the `filesystem` but haven't looked into that.

**Comment by Ayuto** [comment] 2021-02-10 12:13
Goo idea! But we have to remember that resource files could also be located in VPK files. Maybe our ``SourceFile`` class can help? That should also fix resolving the paths.

**Comment by jordanbriere** [comment] 2021-02-10 15:20
> 
> 
> Goo idea! But we have to remember that resource files could also be located in VPK files. Maybe our `SourceFile` class can help? That should also fix resolving the paths.

Ran a quick test, and yes, it seems to do the trick:

```cpp
.def("load_from_file",
	&KeyValuesExt::LoadFromFile,
	"Load KeyValues data from a file and return a new KeyValues instance on success.",
	(arg("file_name"), arg("encoding")="utf-8", arg("errors")="strict", arg("uses_escape_sequences")=false)
).staticmethod("load_from_file")

.def("load_from_file2",
	&KeyValuesExt::LoadFromFile2,
	"Load KeyValues data from a file into an existing KeyValues instance.",
	(arg("file_name"), arg("encoding")="utf-8", arg("errors")="strict")
)
```

```cpp
static boost::shared_ptr<KeyValues> LoadFromFile(const char *szFile, const char *szEncoding, const char *szErrors, bool bUsesEscapeSequences)
{
	KeyValues* pKeyValues = new KeyValues("");
	pKeyValues->UsesEscapeSequences(bUsesEscapeSequences);

	try {
		LoadFromFile2(pKeyValues, szFile, szEncoding, szErrors);
	}
	catch (error_already_set &) {
		pKeyValues->deleteThis();
		throw_error_already_set();
	}

	return boost::shared_ptr<KeyValues>(pKeyValues, &__del__);
}

static bool LoadFromFile2(KeyValues* pKeyValues, const char *szFile, const char *szEncoding, const char *szErrors)
{
	SourceFile *pFile = SourceFile::Open(szFile, "rb");

	bool bResult;
	try {
		object content = object(handle<>(pFile->Read(-1))).attr("decode")(szEncoding, szErrors);
		bResult = KeyValuesExt::LoadFromBuffer2(pKeyValues, extract<const char *>(content));
	}
	catch (error_already_set &) {
		bResult = false;
	}

	pFile->Close();
	delete pFile;

	if (PyErr_Occurred())
		throw_error_already_set();

	return bResult;
}
```

```python
from keyvalues import KeyValues

path = 'resource/cstrike_english.txt'

# UnicodeDecodeError
kv = KeyValues.load_from_file(path)

# {}
kv = KeyValues.load_from_file(path, errors='ignore')
print(kv.as_dict())

# KeyError: "Key 'Radio Responses/Reports\r\n\r\n1. \\' does not exist."
kv = KeyValues.load_from_file(path, 'utf-16')
print(kv.as_dict())

# Works
kv = KeyValues.load_from_file(path, encoding='utf-16', uses_escape_sequences=True)
print(kv.as_dict())
```

**Comment by Ayuto** [comment] 2021-02-10 21:46
That looks good! Though, it's a little bit slow, so I tried using [PyUnicode_Decode](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Decode) and the filesystem directly, but didn't notice any speed improvements. So, the call back to Python doesn't seem to be the costly part. However, it's not like you need to load thousands of files every second, so it's probably fine as it is.

>Also, instead of the 2 naming perhaps we could do:

Hmm, that doesn't really explain the difference to me. I would rather use something like this:
```python
KeyValues.load_from_<file/buffer> # Get a new KeyValues
keyvalues.load_from_<file/buffer>_in_place # Load into existing self
```

**Comment by jordanbriere** [comment] 2021-02-10 22:15
> That looks good! Though, it's a little bit slow, so I tried using [PyUnicode_Decode](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Decode) and the filesystem directly, but didn't notice any speed improvements. So, the call back to Python doesn't seem to be the costly part. However, it's not like you need to load thousands of files every second, so it's probably fine as it is.

I used `decode` mainly so that boost manage the reference. Though, the costly part is likely related to the size of that file (thousands of lines dissected/tokenized into keys/values).



> Hmm, that doesn't really explain the difference to me. I would rather use something like this:
> 
> ```python
> KeyValues.load_from_<file/buffer> # Get a new KeyValues
> keyvalues.load_from_<file/buffer>_in_place # Load into existing self
> ```

I'm fine with whatever. I have a personal preference for `KeyValues.from_file` though, since it is consistent with other static constructors (`Entity.from_inthandle`, `Player.from_userid`, etc.) and read well as "returns a KeyValues from file" but I'm fine with either regardless. Nothing can really be worst than the current `2` to me. 😄

**Comment by Ayuto** [comment] 2021-02-10 22:22
>'m fine with whatever. I have a personal preference for KeyValues.from_file though, since it is consistent with other static constructors (Entity.from_inthandle, Player.from_userid, etc.) and read well as "returns a KeyValues from file" but I'm fine with either regardless. Nothing can really be worst than the current 2 to me. 😄

That's true! In that case we should discard the ``load_`` from their names.

**Closed** 2021-02-10 23:07 UTC
Labels: bug
