### ISSUE TITLE
ImportError: libffi.so.6: cannot open shared object file: No such file or directory (Docker)

### ISSUE THREAD

**Issue by NosferatuJoe** [Source-Python-Dev-Team/Source.Python#378] opened 2021-01-17 01:11 UTC
OS: Ubuntu 18.04

A friend of mine @Soren90 is trying to create a docker image for CSGO which includes source-python.
Now CSGO works fine but we're having trouble with getting source python installed, it keeps throwing this error:

```
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
#[Source.Python] Failed to unload the main module.
#Traceback (most recent call last):

  File "/home/steam/csgo/csgo/addons/source-python/packages/source-python/__init__.py", line 77, in <module>
    from loggers import _sp_logger  # It's save to import this here

  File "/home/steam/csgo/csgo/addons/source-python/packages/source-python/loggers.py", line 24, in <module>
    from core import AutoUnload

  File "/home/steam/csgo/csgo/addons/source-python/packages/source-python/core/__init__.py", line 30, in <module>
    from urllib.request import urlopen

  File "/home/steam/csgo/csgo/addons/source-python/Python3/urllib/request.py", line 84, in <module>
    import base64

  File "/home/steam/csgo/csgo/addons/source-python/Python3/base64.py", line 11, in <module>
    import binascii

ImportError: libz.so.1: cannot open shared object file: No such file or directory
```
And yes libz.so.1 is installed and so are all dependencies mentioned in the SP's wiki

**Comment by jordanbriere** [comment] 2021-01-17 01:13
> And yes libz.so.1 is installed.

Make sure it is the 32 bit version as stated in the [Installation Requirements](http://wiki.sourcepython.com/general/installation.html).

**Comment by Ayuto** [comment] 2021-01-17 01:14
Did he check the installation requirements?
http://wiki.sourcepython.com/general/installation.html#linux

The correct version of zlib must be installed.

**Comment by NosferatuJoe** [comment] 2021-01-17 01:18
Accidentally added a previous exception. This is the current one:

`[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):

  File "/home/steam/csgo/csgo/addons/source-python/packages/source-python/__init__.py", line 98, in load
    setup_sqlite()

  File "/home/steam/csgo/csgo/addons/source-python/packages/source-python/__init__.py", line 470, in setup_sqlite
    import ctypes

  File "/home/steam/csgo/csgo/addons/source-python/Python3/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array

ImportError: libffi.so.6: cannot open shared object file: No such file or directory`

Thanks a lot for the quick responses btw, greatly appreciated!

**Comment by NosferatuJoe** [comment] 2021-01-17 01:21
> Did he check the installation requirements?
> http://wiki.sourcepython.com/general/installation.html#linux
> 
> The correct version of zlib must be installed.

Yes he checked the installation instructions and installed the dependencies

**Comment by xxauroraxx** [comment] 2021-01-17 07:09
As mentioned, the CORRECT VERSION of the dependencies must be installed.
Only the newest version of zlib will be installed with apt.

**Comment by NosferatuJoe** [comment] 2021-01-17 07:52
@xxauroraxx well it's kind of confusing since the wiki is telling you to use apt.. 

Besides that, we fixed the zlib issue, now we're having trouble with libffi. So the latest error mentioned above is the actual one we're having now.

We already tried doing apt libffi6, even going to repo's to install the i386. We can't get it to work, surely we must be missing something..

**Comment by jordanbriere** [comment] 2021-01-17 08:16
> 
> 
> @xxauroraxx well it's kind of confusing since the wiki is telling you to use apt..
> 
> Besides that, we fixed the zlib issue, now we're having trouble with libffi. So the latest error mentioned above is the actual one we're having now.
> 
> We already tried doing apt libffi6, even going to repo's to install the i386. We can't get it to work, surely we must be missing something..

What's the result of `locate libffi.so.*`?

**Comment by Doldol** [comment] 2021-01-17 08:41
Maybe this helps, these are the lines that setup my ubuntu 18 docker container for a CSS server. You don't need `unionfs-fuse` and probably `wget` (experiment with it) in there for a normal setup, so you can leave that out, but I wanted to be sure to show a working example

```docker
FROM ubuntu:18.04

# Prepare Enviroment
ENV DEBIAN_FRONTEND noninteractive
RUN dpkg --add-architecture i386 && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install lib32gcc1 lib32stdc++6 lib32tinfo5 zlib1g wget unionfs-fuse zlib1g:i386 libffi6:i386
RUN apt-get -y install libc6-dbg gdb #for debug
```

**Comment by NosferatuJoe** [comment] 2021-01-17 11:12
Ok so yesterday he tried these but one of them didnt exist in the repos:

apt-get install zlib1g:i386
apt-get install libffi6:i386

So he can install zlib1g:i386, but not libffi6:i386

**Comment by NosferatuJoe** [comment] 2021-01-17 11:17
> > @xxauroraxx well it's kind of confusing since the wiki is telling you to use apt..
> > Besides that, we fixed the zlib issue, now we're having trouble with libffi. So the latest error mentioned above is the actual one we're having now.
> > We already tried doing apt libffi6, even going to repo's to install the i386. We can't get it to work, surely we must be missing something..
> 
> What's the result of `locate libffi.so.*`?

It depends if he installs libffi6 it will find the 64bit version, which doesn't work. But it cannot find the package libffi6:i386 when he tries to install.

**Comment by jordanbriere** [comment] 2021-01-17 11:42
> 
> 
> > > @xxauroraxx well it's kind of confusing since the wiki is telling you to use apt..
> > > Besides that, we fixed the zlib issue, now we're having trouble with libffi. So the latest error mentioned above is the actual one we're having now.
> > > We already tried doing apt libffi6, even going to repo's to install the i386. We can't get it to work, surely we must be missing something..
> > 
> > 
> > What's the result of `locate libffi.so.*`?
> 
> It depends if he installs libffi6 it will find the 64bit version, which doesn't work. But it cannot find the package libffi6:i386 when he tries to install.

Likely because you didn't configure your [multiarch](https://wiki.debian.org/Multiarch/HOWTO#Usage) properly. You have to add the i386 architecture (just like the example posted by @Doldol above illustrates) then update the list otherwise dpkg won't find it.

**Comment by NosferatuJoe** [comment] 2021-01-17 13:17
Also tried what @Doldol advised but still not working.. This is sooo frustrating :/

This is what we use to build the docker image:
https://github.com/kaimallea/csgo/blob/master/Dockerfile

**Comment by Soren90** [comment] 2021-01-17 16:00
Hello guys,
  
To start with, just want to thank everyone. Your willingness to help has been outstanding! 
  
I've have been itching my head for a while yesterday because of this issue but it's now solved. I've been trying to reproduce the issue me and @NosferatuJoe had yesterday, but for some reason it just works now. For some reason i could install ```zlib1g:i386``` but ```libffi6:i386``` could not be found in the repository. I don't know if I've installed some dependency that made ```libffi6:i386``` obsolete and therefore not installable or if there was some wierd issue with the repository cache yesterday. But i rebuild the containers ~50 times.
  
Even magic tricks are cool and such, but in this case i really don't like that i cannot figure out why it just working. :(
  
If anyone else sees this issue and have the same problem as me, i just did this:
  
```
RUN set -xo pipefail \
      && dpkg --add-architecture i386 \
      && apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --no-install-suggests -y \
          lib32gcc1 \
          lib32stdc++6 \
          ca-certificates \
          net-tools \
          locales \
          curl \
          unzip \
          git \
          vim \
          wget \
          zlib1g:i386 \
          libffi6:i386 \
```

**Comment by xxauroraxx** [comment] 2021-01-17 17:21
To clarify a point, I originally said the latest version of zlib would be
installed through apt. I meant to say libffi. If I remember correctly, only
version 7 is available through apt.

**Closed** 2021-01-18 01:32 UTC
Labels: not a bug
